local game = require("assets.scripts.game")
function init(self)
	self.sound = false
	if game.death == 0 then
		sound.play("#s1", {}, function ()
			sound.play("#s2", {}, nil)
		end)
	end
end

function on_message(self, message_id, message, sender)
	if message_id == hash("door_open") and not self.sound then
		self.sound = true
		sound.stop("#s1", {})
		sound.stop("#s2", {})
		sound.play("#s3", {}, function ()
			sound.play("#s4", {}, nil)
		end)
	end
end